### ISSUE TITLE
Namespace в xsd

### ISSUE THREAD

**Issue by SergeyTrifonov** [1C-Company/DirectBank#18]
Добрый день.

В приведенных xsd указывается namespace "http://directbank.1c.ru/XMLSchema".
В 1С (Предприятие 8.3.8.2054) используется другой "http://bank.1c.ru/XMLSchema".
Какой из них правильный?

**Comment by SevDmitry** [comment]
При первоначальном получении настроек обмена из банка программе не известная версия формата, которая используется на стороне банка, поэтому запрос аутентификации по сертификату отправляется в старом формате 2.03, у который было пространство имен "http://bank.1c.ru/XMLSchema".
Это сделано для обратной совместимости, чтобы не была нарушена работа для банков, которые по какой-то причине еще не перешли на схему 2.1.1 с пространством имен "http://directbank.1c.ru/XMLSchema".
Мы можете игнорировать пространство имен или оставить как есть. В следующей версии БЭД мы планирует отказаться от версии формата 2.03, и отправлять все запросы в формате 2.1.1

**Comment by SergeyTrifonov** [comment]
Понятно, спасибо за ответ. 
Можно ли где-нибудь ознакомиться отличиями в форматах? И есть ли схемы по формату 2.03 (в данном репозитории найти не смог)?

**Comment by SevDmitry** [comment]
Файл прикрепил, только удалите расширение txt.



[Версия 2.03.zip.txt](https://github.com/1C-Company/DirectBank/files/773990/2.03.zip.txt)

**Comment by SergeyTrifonov** [comment]
Спасибо!
