### ISSUE TITLE
Шифрование канала

### ISSUE THREAD

**Issue by EZabelin** [1C-Company/DirectBank#2]
Добрый день!

В тексте описания (https://github.com/1C-Company/DirectBank/blob/master/doc/common-section/data-security.md#-Шифрование-данных-при-передаче) указано:
"Передача данных между Клиентом и Банком осуществляется только по зашифрованному каналу (протокол TLS 1.0/1.2), поднимаемом на сертификате Банка (по алгоритму RSA)."
 
Вопросы:
1) Каким образом можно включить шифрование трафика на клиентской стороне?
2) Где надо указать параметр, чтобы шифрованный канал работал по протоколу TLS 1.2?

**Comment by SevrD** [comment]
1) Шифрование включается автоматически, если в адресе сервера банка прописан "https". В противном случае (когда указывается "http"), трафик не шифруется.
2) Какой именно будет использоваться протокол для шифрованного соединения, задается на стороне сервера банка, клиентское ПО подстраивается автоматически.
