### ISSUE TITLE
Формат 2.1.1. Назначение элемента "Digest"

### ISSUE THREAD

**Issue by BSSAnalytics** [1C-Company/DirectBank#21]
Здравствуйте. 
Подскажите, пожалуйста, чем заполняется содержимое элемента "Digest", и для чего он используется?

**Comment by SevDmitry** [comment]
Digest используется для нетипового варианта обмена с использованием внешнего модуля.
В данное поле могут помещаться фактические данные, которые формирует и подписывает внешний модуль.

**Comment by BSSAnalytics** [comment]
Спасибо
