### ISSUE TITLE
Значение параметра CustomerID при аутентификации по закрытому ключу

### ISSUE THREAD

**Issue by ksolovyev-alfabank** [1C-Company/DirectBank#3]
Перед получением настроек обмена с банком в автоматическом режиме необходимо пройти аутентификацию (LogonCert), а для аутентификации в заголовке в параметре CustomerID должен быть передан Уникальный идентификатор Клиента, правильно ли понимаю, что в CustomerID (при аутентификации) будет передан ноль?

**Comment by SevrD** [comment]
Верно, будет передан ноль
