### ISSUE TITLE
Запрос выписки банка и состояния электронного документа

### ISSUE THREAD

**Issue by ahmedovadin** [1C-Company/DirectBank#32]
Добрый день, подскажите пожалуйста как должны выглядеть  
запросы по получению выписки банка и состоянию элекронного документа 
по какому URL 
POST https://dbogate.demobank.ru/?
должен ли xml файл помещаться в транспортный контейнер
должны ли эти запросы отправлятся методом SendPack ? (https://dbogate.demobank.ru/SendPack)

**Comment by SevDmitry** [comment]
> как должны выглядеть
> запросы по получению выписки банка и состоянию элекронного документа
Отправка запроса
POST https://dbogate.demobank.ru/SendPack
Получение ответа:
GET https://dbogate.demobank.ru/GetPackList?date=16.02.2015%2011:25:32
+
GET https://dbogate.demobank.ru/GetPack?id=50214585876

> должен ли xml файл помещаться в транспортный контейнер
Должен

> должны ли эти запросы отправлятся методом SendPack ? (https://dbogate.demobank.ru/SendPack)
Должны
