### ISSUE TITLE
простой тип edo:IDType

### ISSUE THREAD

**Issue by ahmedovadin** [1C-Company/DirectBank#33]
Добрый день, подскажите пожалуйста
может ли идентификатор с типом **edo:IDType** и форматом строки - содержать в себе только числа ?

есть ли ограничения на тип IDType, какие символы он должен/ не должен содержать в себе?

есть ли ограничения на идентификатор транспортного контейнера (GUID), какие символы он должен/ не должен содержать в себе?

возможна ли реализация другого варианта: на стороне банка  идентификатору транспортного контейнера (GUID)  с форматом строки присвоить значение состоящее только из чисел?

**Comment by SevDmitry** [comment]
Добрый день.
> может ли идентификатор с типом edo:IDType и форматом строки - содержать в себе только числа ?

Да

> есть ли ограничения на тип IDType, какие символы он должен/ не должен содержать в себе?

Ограничением является только длина. Сейчас в решениях 1С указала максимальная длина 36 символов

> есть ли ограничения на идентификатор транспортного контейнера (GUID), какие символы он должен/ не должен содержать в себе?

Ограничение только на длину - 80 символов

> возможна ли реализация другого варианта: на стороне банка идентификатору транспортного контейнера (GUID) с форматом строки присвоить значение состоящее только из чисел?

Возможна

**Comment by ahmedovadin** [comment]
Благодарю @SevDmitry
