### ISSUE TITLE
Версия протокола

### ISSUE THREAD

**Issue by an-kuznetsov** [1C-Company/DirectBank#38]
Подскажите пожалуйста, где можно найти схемы и описания для версии 2.02?
Тут нашёл только версии начинающиеся с 2.1._

**Comment by SevDmitry** [comment]
Зачем вам 2.02? Она уже давно не соответствует законодательству.

**Comment by an-kuznetsov** [comment]
Мне нужно реализовать её поддержку со стороны банка. Таковы требования заказчика

**Comment by SevDmitry** [comment]
Актуальные конфигурации 1С не работают с данной версией. Поэтому мы не распространяем неактуальную информацию для избежания проблем в будущем.
Минимальная версия, на которой должен работать банк 2.1.1. Эту версию можем предоставить.

**Comment by an-kuznetsov** [comment]
Спасибо. Сообщу заказчику. Версия можно взять из истории?
https://github.com/1C-Company/DirectBank/tree/9d890bbfd36bc55d9577f997b29bc306df8ebdc4

**Comment by SevDmitry** [comment]
Да
