### ISSUE TITLE
Ошибки размера контейнера/документа

### ISSUE THREAD

**Issue by an-kuznetsov** [1C-Company/DirectBank#39]
Добрый день.
У вас в описании указаны вот такие ошибки

2003 | Недопустимый размер транспортного контейнера | Размер транспортного контейнера не соответствует допустимому диапазону от 0 до  < NNN >

2204 | Недопустимый размер электронного документа | Размер электронного документа не соответствует допустимому диапазону от 0 до < NNN >

В каких единицах эти ошибки и как на них будет реагировать 1С

Особенно интересует ошибка по контейнеру.
Если я верну что контейнер слишком большой, то разобьёт ли его 1С автоматически на части?
Мне важно минимизировать проблемы клиента который использует 1С и предоставить инструкции службе поддержке банка если они нужны.

**Comment by an-kuznetsov** [comment]
Тоесть из 1С всегда приходит 1 документ в одном контейнере? Я правильно понял?
А обратно 1С поддерживает несколько документов в одном контейнере?

**Comment by SevDmitry** [comment]
Правильно. Сейчас всегда приходит 1 документ в одном контейнере.
Работа с входящим контейнером, содержащим несколько документов, поддерживается.

**Comment by an-kuznetsov** [comment]
Спасибо.
А есть ли проработки вопроса когда 1С начнет паковать несколько документов в один контейнер? Что планировалось заложить в ошибку 2003? Количество байт/килобайт/мегабайт или количество документов?

**Comment by SevDmitry** [comment]
Данный вопрос еще не прорабатывался

**Comment by an-kuznetsov** [comment]
Спасибо
