### ISSUE TITLE
Правила перехода между статусами ЭД

### ISSUE THREAD

**Issue by av-parakhin** [1C-Company/DirectBank#41]
Добрый день, подскажите пожалуйста, существуют ли какие-то правила перехода(workflow) между статусами ЭД в 1С или документ может перейти из любого статуса в любой? Если правила существуют, то где их можно посмотреть?

**Comment by SevDmitry** [comment]
Документ может перейти из любого статуса в любой

**Comment by av-parakhin** [comment]
Спасибо!
