### ISSUE TITLE
Работа с различными версиями запросов/контейнеров/документов

### ISSUE THREAD

**Issue by eevgeniy86** [1C-Company/DirectBank#42]
Добрый день!

Подскажите, пожалуйста, регламентируется ли как-нибудь работа с различными версиями электронного обмена у разных сущностей в одном запросе?

Например, если на стороне Банка получаем запрос SendPack с версией 2.2.1 в заголовке, при этом, контейнер в запросе имеет версию 2.1.1, а документ в контейнере версию 2.1.2, как должен формироваться ответ? Можно ли сформировать ответный контейнер и документ в нем в версии 2.2.1 (в соответствии с заголовком запроса), либо версия контейнера/документа в ответе должна соответствовать версиям контейнера/документа в запросе?

**Comment by SevrD** [comment]
Из 1С данные должны приходить с одинаковой версией. 

> Можно ли сформировать ответный контейнер и документ в нем в версии 2.2.1 (в соответствии с заголовком запроса), либо версия контейнера/документа в ответе должна соответствовать версиям контейнера/документа в запросе?

Можно

**Comment by eevgeniy86** [comment]
Т.е. можно ориентироваться только на версию, получаемую в заголовке и игнорировать версии контейнеров и документов?

**Comment by SevrD** [comment]
Верно

**Comment by eevgeniy86** [comment]
Спасибо!
