### ISSUE TITLE
Формат ТК отправленного из банка в 1С

### ISSUE THREAD

**Issue by ksolovyev-alfabank** [1C-Company/DirectBank#5]
Добрый день!

Правильно ли я понимаю, что банк все свои ответы оборачивает в контейнер согласно XML-схеме ответа банк.сервиса?

**Comment by SevrD** [comment]
Правильно,  банк все свои ответы оборачивает в контейнер по схеме [ResultBank](https://github.com/1C-Company/DirectBank/blob/master/doc/common-section/type-tables.md#edo-ResultBank)
