### ISSUE TITLE
Выписка. Значение поля TransitionKind для разных типов документов

### ISSUE THREAD

**Issue by naty-stolayrova** [1C-Company/DirectBank#50]
Добрый день!

Подскажите, верно ли определены значения поля TransitionKind для следующих документов в Выписке:

- Платежное поручение (docKind = 10) --> TransitionKind = 01
- Платежное требование (docKind = 11) --> TransitionKind = 02
- Инкассовое поручение (docKind = 12) --> TransitionKind = 06
- Внутренний банковский документ (docKind = 13) --> TransitionKind = ???
- Мемориальный ордер (docKind = 16) --> TransitionKind = 09
- Платежный ордер (docKind = 17) --> TransitionKind = 16
- Банковский ордер |(docKind = 108 --> TransitionKind = 17
- Объявление на взнос наличными (docKind = 24) --> TransitionKind = 04
- Денежный чек (docKind = 25) --> TransitionKind = 03

Какое значение принимает поле TransitionKind для внутреннего банковского документа (docKind = 13)

**Comment by SevDmitry** [comment]
05, 07, 08, 10, 11, 12 или 13

**Comment by naty-stolayrova** [comment]
А это для каких документов такие коды TransitionKind?

У меня в вопросе перечислено 9 видов документов, а в ответе - только 7

**Comment by SevDmitry** [comment]
Для docKind = 13. Соотношение один ко многим

**Comment by naty-stolayrova** [comment]
Спасибо)
