### ISSUE TITLE
Как сформировать выписку в XML, чтобы избежать ошибки "Значение не является значением объектного типа (СтатусСоставителя)"?

### ISSUE THREAD

**Issue by pintov** [1C-Company/DirectBank#60]
Добрый день!

При формировании XML по схеме ClientBankExchange мы можем не указывать тэг `ПлатежиВБюджет`.
Но если мы не указываем тэг `ПлатежиВБюджет`, то в методе ОбменСБанкамиСлужебный.ПрочитатьВыпискуXDTO возникает ошибка "Значение не является значением объектного типа (СтатусСоставителя)" в следующем коде:
```bsl
Если НЕ ЭлементПлатежа.РеквизитыПлатежа = Неопределено Тогда
	РеквизитыПлатежа.Добавить(ЗначениеЗаполнено(ЭлементПлатежа.ПлатежиВБюджет.СтатусСоставителя), "ЭтоПлатежВБюджет");
	...
КонецЕсли;
```

Если же мы указываем тэг `ПлатежиВБюджет`, то нет возможности оставить пустым `СтатусСоставителя`, чтобы реквизит платежа `ЭтоПлатежВБюджет` был `Ложь`.
Если поместить в `СтатусСоставителя` два пробела, то всё равно получаем ошибку при десериализации XML.

Проблема начала проявляться в БП 3.0.77.78

**Comment by SevDmitry** [comment]
Проблема известна и будет исправлена в ближайшей версии. Необходимо в схеме ClientBankExchange сделать необязательными все поля в группе ПлатежиВБюджет

**Comment by pintov** [comment]
К сожалению, в новом релизе 3.0.77.89 проблема сохранилась.
Проблема блокирует функционал получения банковских выписок.
Скажите, пожалуйста, когда планируется устранить проблему?

**Comment by SevDmitry** [comment]
Был опубликован патч EF_00_00293663.
На завтра запланирована публикация новой версии БП 3.0.77.91 с исправлением этой проблемы

**Comment by pintov** [comment]
К сожалению, в релизе 3.0.77.95 ни чего не изменилось и мы по прежнему имеем проблему с получением выписок.
Дмитрий, уточните, пожалуйста когда планируется исправить проблему?
![image](https://user-images.githubusercontent.com/5813113/82730603-a2cf9100-9d09-11ea-8edc-624b65d52b0f.png)

**Comment by SevDmitry** [comment]
Минимальное количество 0. Если банк прислал пустое значение, то это ошибка банка.

**Comment by pintov** [comment]
Спасибо.
