### ISSUE TITLE
КодВидаДохода в XDTO пакете ClientBankExchange

### ISSUE THREAD

**Issue by pintov** [1C-Company/DirectBank#64]
Добрый день.

В БП 3.0.77.89, к сожалению, не обнаруживаю КодВидаДохода в XDTO пакете ClientBankExchange и соответственно не вижу в методе `ОбменСБанкамиСлужебный.СформироватьПлатежноеПоручениеCML` добавления в XML тэга КодВидаДохода.
Нам осталось восемь рабочих дней до начала использования поля КодВидаДохода.
Подскажите, пожалуйста, когда планируется добавить КодВидаДохода в ClientBankExchange?

**Comment by SevDmitry** [comment]
КодВидаДохода не будет добавлен в пакет ClientBankExchange, т.к. это устаревший формат обмена.

**Comment by pintov** [comment]
В настоящий момет ClientBankExchange используется для DirectBank через внешнюю обработку.
Я правильно понимаю, что такой вариант интеграции перестанет работать 1го июня 2020г. ?
Или для такого варианта интеграции будет смена формата XML передаваемого во внешнюю обработку на подпись?

**Comment by SevDmitry** [comment]
Обмен через внешнюю обработку тоже давно устарел. Есть обмен через внешнюю компоненту. Если мы добавим новое поле в схему ClientBankExchange то на любую попытку передачи его в банк будет возвращаться ошибка, т.к. там его не ждут.

**Comment by pintov** [comment]
> Обмен через внешнюю обработку тоже давно устарел.
В настоящий момент настройка через внешнюю обработку присутствует в интерфейсе.
Пользователи могут выбрать данный вариант настройки.
Уточните, пожалуйста, когда планируется убрать данную возможность из интерфейса?

**Comment by SevDmitry** [comment]
Когда все банки перейдут на обмен через внешнюю компоненту

**Comment by pintov** [comment]
> Если мы добавим новое поле в схему ClientBankExchange то на любую попытку передачи его в банк будет возвращаться ошибка, т.к. там его не ждут.

Я правильно понимаю, что после 1го июня некоторые банки будут использовать сообщения по схеме ClientBankExchange без поля КодВидаДохода?
Т.е. пользователи будут указывать в платежных поручениях код вида дохода, но он не будет передаваться?

**Comment by SevDmitry** [comment]
Правильно

**Comment by pintov** [comment]
Спасибо!
