### ISSUE TITLE
Версия 1С для тестирования DirectBank

### ISSUE THREAD

**Issue by KonstVa** [1C-Company/DirectBank#67]
Добрый день! 
Есть клиент 1С:Предприятие 8.3, учебная версия (8.3.12.1924) с конфигурацией Бухгалтерия предприятия (учебная), редакция 3.0 (3.0.67.54) (http://v8.1c.ru/buhv8/)

В этой версии нет поддержки формата обменом с банком выше 2.1.2. 
Не могли бы уточнить, в какой версии клиента, в какой конфигурации можно выбрать версию обмена 2.2.2, 2.3.1 или же как обновить клиент, для поддержки обозначенных версий?

**Comment by SevDmitry** [comment]
Поддержка версии 2.2.2 есть в БП 3.0.79.11. Вам нужно обновить вашу версию конфигурации через тот же канал, через который получали текущую версию. Поддержка версии 2.3.1 есть пока только в Библиотеке электронных документов 1.7.2. Можно запросить доступ к стенду с актуальными версиями конфигураций, написав на bank@1c.ru

**Comment by KonstVa** [comment]
Благодарю, спасибо за ответ
