### ISSUE TITLE
Использование в других системах, кроме 1c

### ISSUE THREAD

**Issue by rashuf** [1C-Company/DirectBank#69]
Здравствуйте!
Можно ли использовать эту технологию в других учетных системах, не 1с? На первый взгляд, возможность такая есть, потому что она реализована на кросс-платформенных Web-службах и XML. Только я не понял (возможно, пропустил), что за CustomerID (и еще кое-какие идентификаторы, которые используются в других запросах), идентификатор, который указывается при аутентификации, причем первоначально он может быть пустым. Откуда его можно узнать? И можно ли получить/заказать/купить пару логин-пароль или сертификат, если мы не используем продукты 1с, но заинтересованы в технологии DirectBank?

**Comment by SevDmitry** [comment]
Можно. CustomerID возвращает банк при запросе настроек.
Покупать ничего не нужно, достаточно реализовать протокол и обмениваться с любыми банками из списка подключенных. При этом банк даже не будет знать из какой программы приходят запросы.

**Comment by rashuf** [comment]
Спасибо!
