### ISSUE TITLE
БИК в блоке отправителя .../Sender/Bank/@bic

### ISSUE THREAD

**Issue by naty-stolayrova** [1C-Company/DirectBank#71]
Добрый день!

При заполнении в документах, отправляемых Клиенту от Банка (см. перечень ниже), в блоке Отправителя, в атрибуте ....Sender/Bank/@bic можно ли указать БИК головного офиса Банка? Или обязательно следует указывать БИК того подразделения Банка, в котором обслуживается Клиент?

**Перечень документов, отправляемых Клиенту от Банка:**

- Извещение о состоянии обработки транспортного контейнера (StatusPacketNotice/Sender/Bank/@bic)
- Извещение о состоянии электронного документа (StatusDocNotice/Sender/Bank/@bic)
- Настройки обмена с банком (Settings/Sender/@bic)
- Выписка банка (Statement/Sender/@bic)

Аналогичный вопрос для блока Отправителя в транспортном контейнере, направляемом Клиенту от Банка (Packet/Sender/Bank/@bic)

**Comment by SevDmitry** [comment]
В коде данное значение читается только из Settings/Sender/@bic
Здесь обязательно следует указывать БИК того подразделения Банка, в котором обслуживается Клиент.
В остальных документах может быть любое значение.

**Comment by naty-stolayrova** [comment]
Если у Клиента открыто несколько счетов в одном и том же Банке, но в разных его подразделениях, то в Settings/Sender/@bic можно указать любое из этих подразделений?

**Comment by SevDmitry** [comment]
Нет, клиент будет создавать отдельные настройки обмена для каждого подразделения.
Возвращать нужно такой БИК, о котором просит клиент в заголовке метода GetSettings
https://github.com/1C-Company/DirectBank/blob/master/doc/transport-api/readme.md#getSettings

**Comment by naty-stolayrova** [comment]
В рамках другого вопроса (https://github.com/1C-Company/DirectBank/issues/74) мы выяснили, что счета заводится пользователем в системе 1С вручную. 

Что произойдет в ситуации, когда пользователь забьет в 1С номер счета, который открыт в подразделении №2, но при этом не создаст настройки для подразделения №2? Он сможет по такому номеру счета создать платежку и передать ее в Банк по технологии DirectBank?

**Comment by SevDmitry** [comment]
Если у Подразделения №2 такой же БИК, то сможет.

**Comment by naty-stolayrova** [comment]
а если БИК подразделения №2 отличается от БИК-а подразделения №1?

**Comment by SevDmitry** [comment]
Тогда документ не получится отправить, т.к. нет настройки обмена с таким БИКом
