### ISSUE TITLE
Запрос статуса документа после статуса "исполнен" возвращает "принят"

### ISSUE THREAD

**Issue by TrunovS** [1C-Company/DirectBank#72]
Доброго времени суток!

Столкнулись с таким поведением банка:
- отправляем документ PayDocRu
- банк возращает статус "Принят"
- ожидаем измения статуса на "Исполнен"
- Если делаем запрос статуса документа после получения статуса "Исполнен" банк всегда возвращает статус "Принят".

Выходит, что если информация о предыдущих статусах будет недоступна, ответ на запрос статуса будет не актуальным?

Подскажите такое поведение вписывается в требования 1С ДиректБанк?
Должен ли банк при запросе статуса всегда формировать последний актуальный статус или это требование не регламентируется?

**Comment by SevDmitry** [comment]
На запрос статуса банк должен возвращать всегда текущий актуальный статус.
Если возвращает "старый" статус - то это ошибка на стороне банка.

**Comment by TrunovS** [comment]
> На запрос статуса банк должен возвращать всегда текущий актуальный статус.
> Если возвращает "старый" статус - то это ошибка на стороне банка.

Спасибо!
