### ISSUE TITLE
Ошибка 2012 - Некорректное имя файла электронного документа

### ISSUE THREAD

**Issue by naty-stolayrova** [1C-Company/DirectBank#73]
Добрый день!

Я правильно понимаю, что ошибка 2012 - "Некорректное имя файла электронного документа" формируется, если в имени файла указаны следующие  символы:

/" - двойные ковычки
/' - одинарные ковычки
/< - открывающийся тег
/> - закрывающийся тег
/& - амперсанд

Или проверка идет не на присутствие этих символов? Если не на них, то в чем заключается проверка?

**Comment by SevDmitry** [comment]
Да, проверка на недопустимые символы в имени файла.
