### ISSUE TITLE
Синхронизация счетов

### ISSUE THREAD

**Issue by naty-stolayrova** [1C-Company/DirectBank#74]
Добрый день, 

Подскажите, в рамках взаимодействия Банка и Клиента через 1С-DirectBank происходит ли синхронизация счетов Клиента, открытых в этом Банке? 

Вопрос связан с тем, что при автоматическом запросе файла настроек Клиент указывает номер счета. А откуда 1С знает о номере счета, который открыт в Банке? Этот номер счета (или даже несколько номеров) заводится в 1С вручную? Или при подключении 1С-DirectBank есть некий процесс отвечающий за синхронизацию счетов?

**Comment by SevDmitry** [comment]
Добрый день.
Клиент заводит номер счета в программу вручную.
Как правило, при начале работы в программе 1С, клиент вводит реквизиты организации в первую очередь.
Потом подключает прямой обмен с банком.
Очень редко бывают сценарии, когда клиент ввел только название организации, ИНН и КПП и начал подключение обмена с банком. Если номер счета в заголовке для вас обязателен, возвращайте ошибку с понятным текстом.
