### ISSUE TITLE
Данные об Издателе (issuer) в подписи документа

### ISSUE THREAD

**Issue by naty-stolayrova** [1C-Company/DirectBank#75]
Добрый день!

В ходе тестирования обнаружили, что в атрибуте подписи x509IssuerName содержится только CN издателя сертификата. Для корректного поиска сертификата в банковском хранилище нужна информация об издателе в виде: "CN=CRYPTO-PRO Test Center 2, O=CRYPTO-PRO LLC, L=Moscow, C=RU, EMAILADDRESS=support@cryptopro.ru (EMAILADDRESS=support@cryptopro.ru)". 

Возможно ли извлечь эту информацию из самой подписи?

**Comment by SevDmitry** [comment]
Конечно, подпись содержит сертификат

**Comment by naty-stolayrova** [comment]
Сам сертификат сгенерирован по стандарту X.509 ?

**Comment by SevDmitry** [comment]
Да
