### ISSUE TITLE
DocumentType ExtId

### ISSUE THREAD

**Issue by msput86** [1C-Company/DirectBank#78]
В DocumentType есть опциональный элемент ExtId. Рааскажите в каких случаях он проставляется? Для входящих и исходящих электронных документов.
Правильно ли я понмаю, что если в  документе (StatusDocNotice, CancelationRequest) - проставлен ExtId, то и во внешнем DocumentType он должен быть проставлен?

**Comment by SevDmitry** [comment]
Если банк возвращает StatusDocNotice, то в ExtId должен быть id от ранее полученного от клиента PayDocRu, чтобы было понятно, о статусе какого документа сообщает банк. 
Клиент отправляет в банк CancelationRequest и в ExtId указывает id от ранее отправленного в банк PayDocRu, который он решил отозвать.
