### ISSUE TITLE
Порядок формирования ответов

### ISSUE THREAD

**Issue by msput86** [1C-Company/DirectBank#79]
Подскажите пожалуйста, правильно ли понимаю общую последовательность:
1) При получении входящего ТК (транспортный контейнер). Можно всегда  обрабатывать его асинхронно, при этом нужно вернуть некий идентификатор
2) Когда начинаем разбор ТК - возвращаем ТК с StatusPacketNotice (c ошибкой, или успехом) - в котором есть идентификатор из шага 1.
3) Если разбор на шаге 2 успешный - начинаем разбирать документы.  Если документ содержит ошибку - формируем ТК с StatusDocNotice(в нем ошибка). При этом нужно указать в statusDocNotice extId = id обрабатываемого документа с ошибкой.
4) если документ валидный - пытаемся его ставим его в очередь на исполнение. При этом нужно сформировать ТК и указать в statusDocNotice extId = id обрабатываемого документа, + статус (Принят).
5)Если на шаге 2 пришел запрос статуса - то на шаге 4 мы возвращаем статус запрашиваемого документа?

**Comment by SevDmitry** [comment]
1-4 верно. 5 - это отдельный процесс. Если пришел запрос статуса, то нужно сформировать statusDocNotice и поставить в очередь на отправку клиенту.
