### ISSUE TITLE
запрос-пробник

### ISSUE THREAD

**Issue by msput86** [1C-Company/DirectBank#80]
Добрый день.
1С посылает запрос:
`﻿<?xml version="1.0" encoding="UTF-8"?>
<Packet xmlns="http://directbank.1c.ru/XMLSchema" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="5a68df49-f7f1-45c3-8984-083692c4eea1" formatVersion="2.3.1" creationDate="2020-11-17T10:23:39" userAgent="1С - БЭД: 1.7.2.66; БухгалтерияПредприятия: 3.0.83.25">
	<Sender>
		<Customer id="227" name="Открытое акционерное общество &quot;Строитель&quot;" inn="2242000758" kpp="224201001"/>
	</Sender>
	<Recipient>
		<Bank bic="044525266" name="АО &quot;Банк ДОМ.РФ&quot;"/>
	</Recipient>
	<Document id="9ea4781b-2bca-4363-aef8-388111899e48" dockind="05" formatVersion="2.3.1">
		<Data>77u/PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxQcm9i
ZSB4bWxucz0iaHR0cDovL2RpcmVjdGJhbmsuMWMucnUvWE1MU2NoZW1hIiB4bWxu
czp4cz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiIHhtbG5zOnhz
aT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiIGlk
PSI5ZWE0NzgxYi0yYmNhLTQzNjMtYWVmOC0zODgxMTE4OTllNDgiIGZvcm1hdFZl
cnNpb249IjIuMy4xIiBjcmVhdGlvbkRhdGU9IjIwMjAtMTEtMTdUMTA6MjM6Mjki
IHVzZXJBZ2VudD0iMdChIC0g0JHQrdCUOiAxLjcuMi42Njsg0JHRg9GF0LPQsNC7
0YLQtdGA0LjRj9Cf0YDQtdC00L/RgNC40Y/RgtC40Y86IDMuMC44My4yNSI+DQoJ
PFNlbmRlciBpZD0iMjI3IiBuYW1lPSLQntCQ0J4gJnF1b3Q70KHRgtGA0L7QuNGC
0LXQu9GMJnF1b3Q7IiBpbm49IjIyNDIwMDA3NTgiIGtwcD0iMjI0MjAxMDAxIi8+
DQoJPFJlY2lwaWVudCBiaWM9IjA0NDUyNTI2NiIgbmFtZT0i0JDQniAmcXVvdDvQ
kdCw0L3QuiDQlNCe0Jwu0KDQpCZxdW90OyIvPg0KPC9Qcm9iZT4=</Data>
	</Document>
</Packet>`
Банк посылает ответ:
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ResultBank xmlns="http://directbank.1c.ru/XMLSchema"><Success><SendPacketResponse><ID>3</ID></SendPacketResponse></Success></ResultBank>`
В итоге ошибка
`Ответ: «Ошибка чтения ответа банка после отправки пакета по настройке: Строитель ОАО - 044525266 АО "Банк ДОМ.РФ"
Ошибка проверки данных XDTO:
Структура объекта не соответствует типу: {http://bank.1c.ru/XMLSchema}ResultBank»`
Почему другой неймспейс?
БухгалтерияПредприятия: 3.0.83.25

**Comment by SevDmitry** [comment]
Не вижу в ответе банка обязательного атрибута formatVersion

**Comment by msput86** [comment]
да, действительно, спасибо.
А неймспейс? `{http://bank.1c.ru/XMLSchema}ResultBank` - это для обратной совместимости?
Не будет ошибки, если присылать в 1С ` xmlns="http://directbank.1c.ru/XMLSchema"`?

**Comment by SevDmitry** [comment]
Программа не увидела в файле версии формата и решила прочитать по схеме 2.02 в которой не было такого атрибута. В той версии был такой неймспейс
